### ISSUE TITLE
Use Regex Matches in Resource Template

### ISSUE THREAD

**Issue by ChevronTango** [blakelead/nsinjector#4]
It would be incredibly powerful for the match groups from the regex used to match the namespace name to be available to the resource template.

**namespace:** `my-ns-1`
**regex:** `my-ns-(?<id>\d+)`
**resources:** 
```
 apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: dev-rolebinding
    subjects:
    - kind: Group
      name: my-group:${id}
    roleRef:
      kind: Role
      name: dev-role
      apiGroup: rbac.authorization.k8s.io
```
